nf-core/sarek

.travis.yml
Jenkinsfile
build.nf
main.nf

- Add Manta
- Add Strelka
- Add StrelkaBP
- Add MuTecT2
- Add Freebayes
- Add Ascat
- Add Controlfreec

Add somatic Variant Callers

---

main.nf

- fix output name for vcf 
**Learn more about contributing:** https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md

fix output name for vcf

---

CHANGELOG.md
conf/test.config

- Remove `PublishDirMode` from `test` profile
- Fix hard link issues at Crick cc @drpatelh 

Remove PublishDirMode from test profile

---

.github/workflows/branch.yml
.travis.yml
CHANGELOG.md
Dockerfile
Jenkinsfile
containers/snpeff/Dockerfile
containers/snpeff/environment.yml
containers/vep/Dockerfile
containers/vep/environment.yml
docs/annotation.md
docs/install_bianca.md
environment.yml
main.nf
nextflow.config
scripts/download_image.sh

- Apply fixes from 2.5.1 
- Bump to 2.5.2dev

Apply fixes from 2.5.1 and bump to 2.5.2dev

---

CHANGELOG.md
docs/containers.md
environment.yml

Following #41
- update tiddit to `2.8.1`

update tiddit to 2.8.1

---

.github/workflows/ci-extra.yml
CHANGELOG.md
docs/usage.md
main.nf
nextflow.config
scripts/run_tests.sh

add split_fastq

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml
CHANGELOG.md
Dockerfile
Jenkinsfile
conf/base.config
conf/test.config
containers/snpeff/Dockerfile
containers/snpeff/environment.yml
containers/vep/Dockerfile
containers/vep/environment.yml
environment.yml
nextflow.config

Restarting dev branch

---

CHANGELOG.md
conf/genomes.config
main.nf

- simplify setting up ch_knownIndels channel

simplify setting up ch_knownIndels channel

---

assets/multiqc_config.yaml
main.nf

This will add an extra `FastQC after trimming` section if trimming is applied.

Added extra fastqc step after trimming

---

main.nf

Fix issue #136: Ascat computes all possible N-T combinations

---

.circleci/config.yml
CHANGELOG.md

Fix  CircleCI building of VEP containers

---

.github/workflows/awstest.yml

Added commit SHA to results and work directory names for each run

github actions aws test

---

CHANGELOG.md
main.nf

More fixes

---

.github/workflows/awstest.yml

PR to try the trigger of the AWS tests

aws test trigger

---

.github/workflows/awstest.yml

Fix github sha variable in awstests Github Actions workflow

aws tests fix github sha

---

.github/RELEASE_CHECKLIST.md
.github/workflows/ci.yml
CHANGELOG.md
README.md

Last minute changes to include to 2.6

---

main.nf

https://github.com/nf-core/sarek/blob/master/main.nf#L154
always throws an error since all stings returned from  `defineAnnoList()` were uppercase but all strings in `annotateTools` go through `.toLowerCase()`

defineAnnoList now returns lowercase

---

CHANGELOG.md
conf/genomes.config
conf/test_annotation.config
docs/usage.md

fix custom genome possibility

---

.github/workflows/ci.yml
CHANGELOG.md
main.nf

While trying to reproduce #187 I stumbled into an issue with `HaplotypeCaller`.
Here is the fix

fix no_intervals for HaplotypeCaller

---

CHANGELOG.md
main.nf

Updated flags for Freebayes germline

Freebayes germline

---

.circleci/config.yml
CHANGELOG.md

extend timeout for pushing to dockerhub

---

.github/workflows/awstest.yml
CHANGELOG.md

No aws test on forks

---

.github/workflows/awsfulltest.yml
.github/workflows/awstest.yml
CHANGELOG.md

We've added the secrets in the organization level and made some changes to the AWS test GitHub actions workflows so these should be updated.

update aws tests GitHub actions workflows

---

.github/workflows/awsfulltest.yml
main.nf

aply changes from comments

---

CHANGELOG.md
docs/containers.md
environment.yml
main.nf

Close #228 
Tested it on my computer and it works, I can push the docker image, so CI will work as well.
@FriederikeHanssen @ggabernet I guess you are the ones to figure if you want it to be merged or not.
They do claim identical results with major speedups.

Switching to bwa-mem2

---

lib/Headers.groovy

add Sarek ascii art to header

---

main.nf
modules/subworkflows/build_indices.nf

CREATE_INTERVALS_BED is now in build_indices subworkflow

---

README.md
bin/scrape_software_versions.py
main.nf
modules/subworkflows/build_indices.nf

all intervals stuff in out of main.nf

---

main.nf
modules/local/merge_mapped_bam.nf

Add merge_bams process

---

.github/workflows/ci.yml
CHANGELOG.md
conf/genomes.config
conf/test_umi.config
conf/test_umi_qiaseq.config
conf/test_umi_tso.config
docs/containers.md
docs/usage.md
environment.yml
main.nf
nextflow.config

add UMI testing + update docs

---

conf/base.config
main.nf

fix issue #268

---

conf/test_germline_variantcalling.config
main.nf
modules/nf-core/software/functions.nf
modules/nf-core/software/gatk_genotypegvcf.nf
modules/nf-core/software/gatk_haplotypecaller.nf
modules/nf-core/software/strelka.nf
nextflow.config

Variantcalling

---

conf/test_annotation.config

fix test_annotation profile

---

CHANGELOG.md
main.nf

Dev remove warning

---

main.nf
nextflow.config
nextflow_schema.json

add option for controlfreec

---

modules/nf-core/software/bwa/mem/main.nf
modules/nf-core/software/bwamem2/mem/main.nf

Correct hash in mulled bwa/bwa-mem2 | samtools containers

---

nextflow_schema.json

fix: cadd_cache is a boolean

---

subworkflows/local/markduplicates_csv.nf
subworkflows/local/prepare_recalibration_csv.nf
subworkflows/local/recalibrate_csv.nf
tests/test_aligner.yml
tests/test_default.yml
tests/test_gatk_spark.yml
tests/test_pair.yml
tests/test_targeted.yml
workflows/sarek.nf

bam -> cram in CSV

---

CHANGELOG.md
modules.json
modules/nf-core/modules/deeptools/bamcoverage/main.nf
modules/nf-core/modules/deeptools/bamcoverage/meta.yml
subworkflows/nf-core/bam_to_cram.nf

This PR updates the module deeptools/bamcoverage to convert `cram` to `bam` before running the `bamcoverage`.

Updated module deeptools/bamcoverage

---

CHANGELOG.md
conf/modules.config

Fix empty folder on intervals

---

CHANGELOG.md
conf/igenomes.config
modules.json
modules/nf-core/modules/ensemblvep/main.nf

update cache version in igenomes.config + update vep module

---

CHANGELOG.md
conf/modules.config

Remove WARNING message for config selector

---

CHANGELOG.md
conf/igenomes.config

fix igenomes config ascat

---

CHANGELOG.md
workflows/sarek.nf

fix issue with AWS megatests

---

conf/modules.config
modules.json
modules/nf-core/modules/snpeff/main.nf
modules/nf-core/modules/snpeff/meta.yml
tests/test_annotation.yml
workflows/sarek.nf

The purpose of this PR is just to include a summary-html-file and a genes-txt-file in the published output from snpEff.
Tests and `git_sha` of `snpeff` in `modules.json` have been updated.

DRAFT: Extending output from snpEff

---

.github/workflows/awsfulltest.yml
.github/workflows/awsfulltest_somatic.yml
CHANGELOG.md
conf/test_full_somatic.config
nextflow.config

add full size tests somatic

---

docs/usage.md

try leveling everything up

---

CHANGELOG.md
workflows/sarek.nf

Simplifying the multiqc config logic.

Simplify multiqc config channels

---

conf/base.config
conf/test_full.config

add split fastq to test full

---

CHANGELOG.md
subworkflows/local/mapping_csv.nf
subworkflows/local/markduplicates_csv.nf
subworkflows/local/prepare_recalibration_csv.nf
subworkflows/local/recalibrate_csv.nf
subworkflows/local/variantcalling_csv.nf

fix path to file in csv files

---

modules.json
modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
modules/nf-core/modules/strelka/germline/main.nf

update modules to match tools' versions

---

CHANGELOG.md
README.md
conf/modules.config

fix when clause for building mapping indexes

---

pyproject.toml

Dev sync 2.5.1

---

.github/workflows/ci.yml
CHANGELOG.md

reduce number of CI tests

---

CHANGELOG.md
conf/igenomes.config
subworkflows/local/prepare_intervals.nf
workflows/sarek.nf

make interval parsing less restrictive

---

CHANGELOG.md
conf/base.config

Adapt resource requests

---

CHANGELOG.md
nextflow.config

More polish

---

CHANGELOG.md
conf/igenomes.config

use chr length file by default since cf is otherwise not working

---

CHANGELOG.md
conf/modules.config
conf/test.config
subworkflows/nf-core/gatk4/tumor_normal_somatic_variant_calling/main.nf

Fix somatic test with mutect2

---

CHANGELOG.md
conf/modules.config

Don't publish unzip files

---

CHANGELOG.md
conf/modules/aligner.config

add rgid, to separate sample info

---

.nf-core.yml

remove poster from linting

---

CHANGELOG.md
nextflow_schema.json

Close #694 
Took a peak at how rnaseq does the input validation and that one works through the website.

Fix validation of input when launching from website

---

conf/test/test.config

prioritze test conf for mutect in tests

---

CHANGELOG.md
lib/WorkflowSarek.groovy

Use putIfAbsent

---

CHANGELOG.md
conf/modules/freebayes.config

freebayes selector still used old sw name

---

CHANGELOG.md
workflows/sarek.nf

cf https://github.com/nf-core/atacseq/pull/222

 Get read of copyTo

---

.github/workflows/ci.yml
.github/workflows/pytest-workflow.yml
CHANGELOG.md
conf/modules/tiddit.config

add NF version to test name

---

docs/output.md
tests/test_recalibrate_from_bam.yml
tests/test_recalibrate_from_cram.yml

review comments

---

.github/workflows/ci.yml
.github/workflows/pytest-workflow.yml
CHANGELOG.md

Fix tests master

---

CHANGELOG.md
nextflow.config

Back to dev

---

CHANGELOG.md
conf/modules/haplotypecaller.config

fix bam output for haplotypecaller

---

CHANGELOG.md
subworkflows/local/bam_variant_calling_somatic_all/main.nf

Fix pair variant calling issue with msisensor

---

CHANGELOG.md
README.md

FEAT: Update README

---

CHANGELOG.md
README.md

@adamrtalbot  you are a lighting-speed question answerer but noticed you were somehow not listed in the contributor list

Add Adam Talbot to contributor list

---

CHANGELOG.md
conf/igenomes.config

Fix missing annotation keys for vep/snpeff

---

CHANGELOG.md
conf/modules/prepare_cache.config
docs/usage.md
nextflow.config
nextflow_schema.json
tests/test_annotation_cache.yml

ADD: Annotation cache usage docs

---

CHANGELOG.md
conf/igenomes.config
conf/modules/annotate.config
conf/test/test.config
conf/test/test_full_germline.config
docs/usage.md
nextflow_schema.json
workflows/sarek.nf

fix genome null with annotation

---

CHANGELOG.md
tests/config/tags.yml

FIX: typos

---

CHANGELOG.md
workflows/sarek.nf

Input validation fixes 

---

CHANGELOG.md
nextflow.config

Codename is the other big lake in Sarek

CHORES: bump to 3.2.0

---

CHANGELOG.md
nextflow_schema.json

Fix pattern for fasta file in the json schema

FIX: pattern for fasta file

---

CHANGELOG.md
lib/WorkflowMain.groovy
lib/WorkflowSarek.groovy
workflows/sarek.nf

working again
why are we not testing that?

FIX: automatic restart from step

---

CHANGELOG.md
docs/output.md

docs update

---

CHANGELOG.md
nextflow.config

CHORES: back to dev

---

CHANGELOG.md
modules.json
modules/nf-core/tabix/bgziptabix/main.nf

Fix typo by removing quay.io in module
cf https://github.com/nf-core/modules/pull/3496

FIX: update bgziptabix module

---

CHANGELOG.md
subworkflows/local/bam_variant_calling_somatic_mutect2/main.nf

FIX: Mutect2 subworkflow

---

CHANGELOG.md
conf/modules/mpileup.config
docs/output.md
subworkflows/local/bam_variant_calling_mpileup/main.nf
subworkflows/local/bam_variant_calling_tumor_only_all/main.nf
tests/test_controlfreec.yml
tests/test_mpileup.yml
workflows/sarek.nf

fix bcftools mpileup

---

conf/modules/aligner.config
conf/modules/markduplicates.config
tests/test_aligner_sentieon_bwamem.yml
workflows/sarek.nf

The following test-cmd didn't publish any bam-files (just bai-files) from SENTIEON_BWAMEM:
```
nextflow run main.nf -profile test_cache,docker --aligner sentieon-bwamem --save_mapped --save_output_as_bam --outdir results
```
Now it does :-)  I tried to improve on some related stuff.  Added some pytests.

Publishing bam from sentieon-bwamem

---

CHANGELOG.md
README.md
lib/WorkflowMain.groovy

Fix Zenodo Links

---

CHANGELOG.md
tests/test_umi.yml
workflows/sarek.nf

Validate umi sentieon

---

CHANGELOG.md
docs/usage.md

Restore proper rendering in usage.md

---

CHANGELOG.md
tower.yml

Greatly improve tower.yml file

---

.github/workflows/ci.yml
.nf-core.yml
CHANGELOG.md

remove push: dev CI trigger

---

CHANGELOG.md
tests/test_aligner_sentieon_bwamem.yml

update checksums due to input csv changes

---

CHANGELOG.md
CITATIONS.md
README.md
nextflow.config

Fix Zenodo ID in manifest

---

CHANGELOG.md
nextflow.config

prepare release

---

.github/workflows/awstest.yml
CHANGELOG.md

fix result path

---

CHANGELOG.md
modules.json
modules/nf-core/controlfreec/assesssignificance/controlfreec-assesssignificance.diff
modules/nf-core/controlfreec/assesssignificance/main.nf

FIX: revert controlfreec-assesssignificance

---

subworkflows/local/bam_variant_calling_somatic_mutect2/main.nf

try better empty channel management for germline ressource in mutect2 subworkflow

---

CHANGELOG.md
assets/slackreport.json

remove extra v for slack report

---

.github/workflows/cloudtest.yml
CHANGELOG.md
conf/test_full_germline_ncbench_agilent.config
nextflow.config

Add test profile for ncbench

---

conf/test.config

Should fix issues in https://github.com/nf-core/sarek/pull/1408

add modules_testdata_base_path

---

.github/workflows/ci.yml
CHANGELOG.md
tests/config/pytesttags.yml
tests/test_sentieon_dnascope_joint_germline.yml
tests/test_sentieon_dnascope_skip_filter.yml
tests/test_sentieon_haplotyper_joint_germline.yml
tests/test_sentieon_haplotyper_skip_filter.yml

update triggered tests

---

README.md

Where is Edmund?

---

.github/workflows/ci.yml

Fix test name

---

CHANGELOG.md
nextflow.config

fix(spark): load spark profile after loading the test profiles

---

CHANGELOG.md
nextflow.config

feat(nf-prov): pin nf-prov to 1.2.2

---

CHANGELOG.md
README.md
nextflow.config

Add new citation

---

CHANGELOG.md
nextflow.config

cf https://github.com/nf-core/tools/pull/2941

feat(wave): add wave profile

---

CHANGELOG.md
README.md

Adding Simon and Ken

---

CHANGELOG.md
conf/modules/trimming.config

Simplify logic in args management

---

README.md

adding myself as contributor

---

CHANGELOG.md
nextflow_schema.json

Typo build_from_index -> build_only_index

---

CHANGELOG.md
conf/test.config
modules.json
modules/nf-core/samtools/bam2fq/environment.yml
modules/nf-core/samtools/bam2fq/main.nf
modules/nf-core/samtools/bam2fq/tests/main.nf.test.snap
modules/nf-core/samtools/collatefastq/environment.yml
modules/nf-core/samtools/collatefastq/main.nf
modules/nf-core/samtools/convert/environment.yml
modules/nf-core/samtools/convert/main.nf
modules/nf-core/samtools/convert/tests/main.nf.test.snap
modules/nf-core/samtools/faidx/environment.yml
modules/nf-core/samtools/faidx/main.nf
modules/nf-core/samtools/faidx/tests/main.nf.test.snap
modules/nf-core/samtools/index/environment.yml
modules/nf-core/samtools/index/main.nf
modules/nf-core/samtools/index/tests/main.nf.test.snap
modules/nf-core/samtools/merge/environment.yml
modules/nf-core/samtools/merge/main.nf
modules/nf-core/samtools/merge/tests/main.nf.test.snap
modules/nf-core/samtools/mpileup/environment.yml
modules/nf-core/samtools/mpileup/main.nf
modules/nf-core/samtools/mpileup/tests/main.nf.test.snap
modules/nf-core/samtools/stats/environment.yml
modules/nf-core/samtools/stats/main.nf
modules/nf-core/samtools/stats/tests/main.nf.test.snap
modules/nf-core/samtools/view/environment.yml
modules/nf-core/samtools/view/main.nf
modules/nf-core/samtools/view/tests/main.nf.test.snap
tests/test_controlfreec.yml

Update samtools to v1.20

---

CHANGELOG.md
modules.json
modules/nf-core/bcftools/annotate/bcftools-annotate.diff
modules/nf-core/bcftools/annotate/environment.yml
modules/nf-core/bcftools/annotate/main.nf
modules/nf-core/bcftools/annotate/tests/main.nf.test
modules/nf-core/bcftools/annotate/tests/main.nf.test.snap
modules/nf-core/bcftools/concat/environment.yml
modules/nf-core/bcftools/concat/main.nf
modules/nf-core/bcftools/concat/tests/main.nf.test.snap
modules/nf-core/bcftools/mpileup/environment.yml
modules/nf-core/bcftools/mpileup/main.nf
modules/nf-core/bcftools/mpileup/tests/main.nf.test.snap
modules/nf-core/bcftools/sort/environment.yml
modules/nf-core/bcftools/sort/main.nf
modules/nf-core/bcftools/sort/tests/main.nf.test.snap
modules/nf-core/bcftools/stats/environment.yml
modules/nf-core/bcftools/stats/main.nf
modules/nf-core/bcftools/stats/tests/main.nf.test
modules/nf-core/bcftools/stats/tests/main.nf.test.snap

Update bcftools to v1.20

---

CHANGELOG.md
conf/igenomes.config

update vep cache version

---

CHANGELOG.md
tests/test_haplotypecaller.yml
tests/test_haplotypecaller_skip_filter.yml

FIX: drop snapshot from Haplotypecaller tests

---

CHANGELOG.md
tests/test_deepvariant.yml

FIX: drop snapshot from Deepvariant tests

---

CHANGELOG.md
workflows/sarek/main.nf

fix flowcell access

---

.github/workflows/ci.yml
CHANGELOG.md
modules.json
subworkflows/nf-core/utils_nfschema_plugin/tests/main.nf.test

Update nf-schema tests that were not failing on lenient mode

---

CHANGELOG.md
README.md

New contributor

---

.github/workflows/nf-test.yml
.github/workflows/pytest.yml

fix actions

---

.github/workflows/pytest.yml

FIX: update cache actions for pytest

---

.github/actions/nf-test/action.yml

Fixing nf-test shards

---

CHANGELOG.md
modules.json
modules/nf-core/ensemblvep/download/environment.yml
modules/nf-core/ensemblvep/vep/environment.yml
modules/nf-core/ensemblvep/vep/main.nf
modules/nf-core/ensemblvep/vep/meta.yml
modules/nf-core/ensemblvep/vep/tests/main.nf.test
modules/nf-core/ensemblvep/vep/tests/main.nf.test.snap
modules/nf-core/snpeff/download/environment.yml
modules/nf-core/snpeff/snpeff/environment.yml
modules/nf-core/snpeff/snpeff/main.nf
modules/nf-core/snpeff/snpeff/tests/main.nf.test
modules/nf-core/snpeff/snpeff/tests/main.nf.test.snap
modules/nf-core/tabix/tabix/environment.yml
subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
subworkflows/nf-core/vcf_annotate_ensemblvep/meta.yml
tests/annotation_merge.nf.test.snap
tests/annotation_vep.nf.test.snap

Update annotation related modules

---

CHANGELOG.md
nf-test.config

Modyfing .nftignore should retrigger tests

---

.github/workflows/nf-test-gpu.yml

fix GHA gpu action

---

CHANGELOG.md
nextflow_schema.json

Fix json schema cf_chrom_len input

---

CHANGELOG.md
conf/base.config

cf https://github.com/nf-core/tools/pull/3564

Make jobs automatically resubmit for exit code 175

---

.github/workflows/nf-test-gpu.yml
.github/workflows/nf-test.yml
CHANGELOG.md

Ensure nf-test runs for all profiles on release

---

CHANGELOG.md
tests/nextflow.config

fix tests when no sentieon server/ENV

---

CHANGELOG.md
nextflow.config

Remove duplicated gpu profile from config

---

CHANGELOG.md
main.nf
nextflow_schema.json
tests/annotation_vep.nf.test

Fails when no dbnsfp_tbi provided when a dbnsfp is

---

CHANGELOG.md
conf/igenomes.config
modules.json
modules/nf-core/ensemblvep/download/environment.yml
modules/nf-core/ensemblvep/download/main.nf
modules/nf-core/ensemblvep/vep/environment.yml
modules/nf-core/ensemblvep/vep/main.nf
modules/nf-core/snpeff/download/environment.yml
modules/nf-core/snpeff/download/main.nf
modules/nf-core/snpeff/download/meta.yml
modules/nf-core/snpeff/snpeff/environment.yml
modules/nf-core/snpeff/snpeff/main.nf
subworkflows/local/samplesheet_to_channel/tests/main.nf.test
tests/annotation_merge.nf.test.snap

Bump snpeff to v5.3 and VEP to 115.2
